[package]
name = "storybook-example"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["web"] }
serde = { workspace = true, features = ["derive"] }
storybook = { workspace = true }
